### ISSUE TITLE
[zabbix] fix monitoring

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/e-services#16]
The web scenarios in the zabbix templates
* Template E-LINK explore ldf
* Template E-ENTITY Freme-NER

are disabled because they do not work. They should be fixed and re-enabled.

**Comment by jnehring** [comment]
@ArneBinder please fix this when you are done with other issues. especially the test for freme ner is important.

**Comment by ArneBinder** [comment]
This should be fixed. @jnehring please close, if it looks alright to you.

**Comment by ArneBinder** [comment]
> Did you also switch off the logging of FREME DEV?
Yes. Just Freme live, freme ner live and the solr server are checked.

**Comment by jnehring** [comment]
Works fine!
