### ISSUE TITLE
e-Translate: request source-lang and target-lang pairs

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/e-services#20]

**Comment by andish** [comment]
Tilde endpoint now returns list of available systems in json format, which includes information about system IDs, domains, language pairs.
Curl:
```curl
curl -X GET -H "Authorization: Basic RlJFTUU6dXxGcjNtM19zJGN1ciQ=" -H "Cache-Control: no-cache" -H "Postman-Token: 58f051a3-ee38-3fb5-72ca-10930f710307" "https://services.tilde.com/configuration/translation"
```
Optional qyery parameter - 'key' (in order to retrieve private systems).

Response example:
```json
{
  "systems": [
    {
      "sourceLanguage": {
        "Code": "nl",
        "Name": {
          "Language": "en",
          "Text": "Dutch"
        }
      },
      "targetLanguage": {
        "Code": "fr",
        "Name": {
          "Language": "en",
          "Text": "French"
        }
      },
      "systemID": "smt-63f939f0-7ebf-4b45-978a-4fa4714c601b",
      "domain": "law",
      "isPrivate": false,
      "status": "standby"
    },
    {
      "sourceLanguage": {
        "Code": "en",
        "Name": {
          "Language": "en",
          "Text": "English"
        }
      },
      "targetLanguage": {
        "Code": "de",
        "Name": {
          "Language": "en",
          "Text": "German"
        }
      },
      "systemID": "smt-c71f6f22-5e2a-4682-a4cc-2d97d38fac5e",
      "domain": "Legal",
      "isPrivate": false,
      "status": "ready"
    } ]
}
```
@jnehring how it would be implemented in FREME server? new endpoint?

**Comment by jnehring** [comment]
@pheyvaer  is this still a requirement? Are you going to use this service?

Do we actually need to provide this as a FREME endpoint? Users could call the service directly.

**Comment by pheyvaer** [comment]
Yes, for the CKEditor plugin.

**Comment by jnehring** [comment]
@bgrusdt please implement a new API endpoint for this.

**Comment by jnehring** [comment]
@pheyvaer how about you request this data directly from tilde? Maybe this is easier then creating a new FREME endpoint for this that merely proxies the data.

**Comment by pheyvaer** [comment]
Works also for us :)

**Comment by jnehring** [comment]
ok then lets do it that way.

**Comment by bjdmeest** [comment]
Thanks! moved to https://github.com/freme-project/CKEditor-Plugin/issues/27 :)
