### ISSUE TITLE
[e-Terminology] Dropped calls

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-services#24]
@koidl reported that calls to e-Terminology get dropped. I checked the logfile and I cannot see log messages that indicate that a calls is dropped because of server overload. It is still possible that the server is overloaded though. I need some more information:
- What exactly do you mean by "Dropped call"? What is the http status code and does FREME provide more information like an error message?
- Is there a way we can reproduce the problem? I mean, is there a specific API call that fails all the time?
- Can you point me to a time when the problem occured? Then I can better search the log files.
- Do you do the same amount of calls to another e-Service also? I want to know if this is e-Terminology specific.
- You mention 10 calls per second. How many calls do you do in parallel?

**Comment by xFran** [comment]
> What exactly do you mean by "Dropped call"? 

Dropping the connection.

> What is the http status code and does FREME provide more information like an error message?

I can't provide status code. Most of the time we get connection timeout.

> Is there a way we can reproduce the problem? I mean, is there a specific API call that fails all the time?

We use multiple services.

> Can you point me to a time when the problem occured? Then I can better search the log files.

Monday and Tuesday i ran some tests. 

> Do you do the same amount of calls to another e-Service also? I want to know if this is e-Terminology specific.

I do the same amount of calls for multiple services. The pipelines to get the labels, we used e-Terminology (this is the service we get connection timeout more often), one Aylien service (no issues here) and some times for testing things I use Open Calais (no issues here)

> You mention 10 calls per second. How many calls do you do in parallel?

Depends of how many websites I crawl but between 1 and 5.

What Apache you run in your server and what version?
If is not too much to ask can you run for me in your server the command "htop" and please send me a screenshot?

**Comment by jnehring** [comment]
We further discussed this via email and now the issue is delayed for some weeks.

**Comment by jnehring** [comment]
@xFran do you still have this problem?

**Comment by jnehring** [comment]
I think we can close this
