### ISSUE TITLE
[e-Link] Can we add data?

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-services#27]
Is it possible to create an e-Link template to insert data into an RDF graph? This would be interesting for WRIPL so they can add data the FREME triple store using the FREME API. It would also be interesting for the DKT project because we have a pipeline and want to persist the outcome in the triple store.

**Comment by m1ci** [comment]
The current implementation of e-Link does not consider such use case.
If one want to insert data into a triple store via the SPARQL interface, this can be done as described in the SPARQL 1.1 Update spec (https://www.w3.org/TR/sparql11-update/). In other words, send Insert SPARQL request to the endpoint.

**Comment by jnehring** [comment]
Thanks for the answer. We will not use e-link to insert data in the triple store but use this approach: https://github.com/freme-project/freme-ner/issues/132
