### ISSUE TITLE
[e-link] unit test fails

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-services#28]
On Jenkins, an e-Link unit test fails.

**Comment by bgrusdt** [comment]
The problem was that no  endpoint was provided when the template is constructed. I changed this and  it  works on Jenkins now.  So I close this.

**Comment by ArneBinder** [comment]
> The problem was that no endpoint was provided when the template is constructed. I changed this and it works on Jenkins now. So I close this. 

This wasn't the problem, but the content of the mockup-endpoint response conflicted in any way with the test case. Sniffing into the reponse of the dbpedia sparql response shows that the DataEnricher receives the following content from the endpoint:

```
# Empty TURTLE
```

After changing the content of the mockup endpoint file `linking-ELINK.ttl` to the above content the test doesn't fail anymore.

**Comment by jnehring** [comment]
> But in any case this (empty enrichment) indicates, that the test setting is not the best to check the linking functionality.

What do you suggest? Using a turtle file with other data?

**Comment by bgrusdt** [comment]
I have had a look at it again. I changed the linking-ELINK.ttl file, which is returned by the mockup-endpoint and on which the sparql query is executed. Now it only contains two triples which contain the resource Berlin which in turn is contained in the NIF-content we sent to the endpoint. 
This works now. I also added a assertTrue statement which makes sure that the response of the e-link request contains the expected information. 
@jnehring @ArneBinder What do you think?

**Comment by jnehring** [comment]
> What do you think?

Sounds good. Lets see what @ArneBinder says about it.

**Comment by jnehring** [comment]
This issue is finished
