### ISSUE TITLE
[e-Translation] implement NIF 2.1

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-services#30]
Please implement changes to implement NIF 2.1 annotations. The use of annotation units should be switched on / off using a parameter "nif-version=2.0" or "nif-version=2.1" with the default value being "2.0"

**Comment by andish** [comment]
Nif version parameter at Tilde endpoints is implemented both for ***e-Translation*** and ***e-Terminology***.
By default is ```&nif-version=2.0```.
Should be implemented also at Freme server side.

**Comment by jnehring** [comment]
This issue is solved
