### ISSUE TITLE
wrong documentation example for e-terminology

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-services#32]
The example in the simple documentation is wrong.
http://api-dev.freme-project.eu/doc/api-doc/simple.html#!/e-Terminology/e_terminology
```
<http://freme-project.eu/>
```

does not contain #offset_0_11

```
  @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
  @prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
  @prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
  @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
  @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
  <http://freme-project.eu/>
      a nif:String , nif:RFC5147String , nif:Context ;
      nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
      nif:endIndex    "11"^^xsd:nonNegativeInteger ;
      nif:isString    "Welcome to Europe"@en.
```

please check also the other examples.

**Comment by jnehring** [comment]
@bgrusdt please use the [nif converter](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/Toolbox%2FNIF-Converter/post_toolbox_nif_converter) to re-create examples for e-translation and e-terminology.

**Comment by bgrusdt** [comment]
I have created and added the [new examples](http://api-dev.freme-project.eu/doc/api-doc/simple.html#!/e-Translation/tildeTranslate).
