### ISSUE TITLE
PUBLIC FREME: external services fails because of "Bad Gateway"

### ISSUE THREAD

**Issue by andish** [freme-project/e-services#37]
For e-Terminology and E-Translation:
```json
{
  "exception": "eu.freme.common.exception.ExternalServiceFailedException",
  "path": "/e-translation/tilde",
  "message": "java.net.UnknownHostException: services.tilde.com: unknown error",
  "error": "Bad Gateway",
  "status": 502,
  "timestamp": 1473059257744
}
```

For E-entity:
https://api.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all 
``` json
{
  "exception": "eu.freme.bservices.filter.proxy.exception.BadGatewayException",
  "path": "/e-entity/freme-ner/documents",
  "message": "Proxy failed: java.net.UnknownHostException: rv2622.1blu.de: unknown error",
  "error": "Bad Gateway",
  "status": 502,
  "timestamp": 1473059069456
}
```

Tested with public version - Full documentation:
http://api.freme-project.eu/doc/current/api-doc/full.html#!/e-Terminology/e_terminology

**Comment by jnehring** [comment]
I could fix this through a restart of FREME live. This is a dublicate of this bug: https://github.com/freme-project/FREMECommon/issues/22
