### ISSUE TITLE
Separate user accounts for Tilde services

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-services#39]
When we install Tilde at our partner sites, we need different user accounts for each partner. So the user acccount needs to be configurable in the application.properties configuration file.

@andish how do we pass authentication credentials to Tilde services? Currently we pass a header "Authentication". Do we have to submit a separate value for Authentication for each installation?

**Comment by andish** [comment]
Authentication is realized using Basic authentication. It means that an authorization token is enough for bringing to global configuration file (it contains encoded username+password). Also URL would be grate if could be placed in configuration file, so we would change api endpoint and authorization without rebuilding the freme server.
So for each e-service following properties would be good to bring to configuration:
1. URL of endpoint;
2. authorization token.

**Comment by jnehring** [comment]
In [e-Translation](https://github.com/freme-project/e-services/blob/master/tilde-services/src/main/java/eu/freme/eservices/tilde/translation/TildeETranslation.java#L136) and [e-Terminology](https://github.com/freme-project/e-services/blob/master/tilde-services/src/main/java/eu/freme/eservices/tilde/terminology/TildeETerminology.java#L147) we send the authentication token in the request header "Authentication" to the Tilde service. So the header will look like

```
Authentication: Basic TOKEN_HERE
```

with TOKEN_HERE being replaced by the token.

Is this correct?

Configuraiton of URL endpoint is already implemented for the unit tests, we just need to document it.

**Comment by andish** [comment]
yes, exactly.

**Comment by jnehring** [comment]
@ArneBinder please

1) make the authentication token a configuration parameter in e-Terminology and e-Translation. Put the configuration in /home/u231015/freme-configs/broker-dev-private.properties on freme-dev because it should not be public. There should be separate parameters for e-Translation and e-Terminology.
2) add documentation about the authentication token parameter and the parameter to configure both API endpoints to http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/e-services.html .

**Comment by jnehring** [comment]
Please do not add the configuration to `/home/u231015/freme-configs/broker-dev-private.properties` but to

* broker-dev
* broker-local
* freme-full

**Comment by bgrusdt** [comment]
Here is what I added to the [documentation](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/e-services.html#tilde-e-terminology). @jnehring is this ok?

**Comment by jnehring** [comment]
Looks good. The functionality is implemented.
