### ISSUE TITLE
Migrate DBPedia Spotlight to new architecture

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-services#4]

**Comment by josauder** [comment]
This is done - moved Service and Unit Test

Dbpedia-Spotlight Endpoint can be configured using `application.properties`.
Parameter `freme.eentity.dbpediaSpotlightEndpointUrl` defaults to `http://spotlight.nlp2rdf.aksw.org/spotlight`

Unit Test tests against mockup endoint at `http://localhost:8080/mockups/file/response.ttl`
