### ISSUE TITLE
e-terminology request breaks

### ISSUE THREAD

**Issue by fsasaki** [freme-project/e-services#47]
See

> curl -X POST "https://api-dev.freme-project.eu/current/e-terminology/tilde?source-lang=en&target-lang=es&mode=full&intype=url&input=http://www.bbc.com/news/magazine-36992955&informat=text/html"

The error message is

> {
  "exception": "eu.freme.common.exception.ExternalServiceFailedException",
  "path": "/e-terminology/tilde",
  "message": "External service failed: {\"Message\":\"TErminology Internal server error. Reason: StringParser failed to parse the RDF string correctly, StringParser auto-detection guessed 'Turtle' but this failed to parse.  RDF string may be malformed or StringParser may have guessed incorrectly\"}",
  "error": "Bad Gateway",
  "status": 502,
  "timestamp": 1476272584878
}

**Comment by andish** [comment]
Hmm, error message says than input not in correct NIF turtle For Tilde endpoint.
What is this - intype=url? Does the FREME server support such input type?

**Comment by fsasaki** [comment]
See 
>  curl -X POST --header "Accept: text/n3" "https://api-dev.freme-project.eu/current/toolbox/nif-converter?intype=url&input=http://www.bbc.com/news/magazine-36992955&informat=text/html" 

and attachment.
[input.txt](https://github.com/freme-project/e-services/files/524375/input.txt)

**Comment by andish** [comment]
Fixed, please check.

**Comment by fsasaki** [comment]
works, thanks!
