### ISSUE TITLE
Update WRIPL e-Link template

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-services#49]
WRIPLs e-Link template (id=4496) needs to be extended to add the most frequent class to the output (see https://github.com/freme-project/freme-ner/issues/160). The SPARQL SELECT query needs to be extended.

**Comment by m1ci** [comment]
should we update the e-Link on dev and live?

**Comment by jnehring** [comment]
Yes both. I can provide you with the necessary admin auth tokens in case you dont have them.

**Comment by jnehring** [comment]
We do not need to update the e-Link template. We need to update the WRIPL filter. I think they use the filter "entities-detailed-info" to convert linked data to JSON or CSV. @xFran am I right?

**Comment by xFran** [comment]
I really don't know what "entities-detailed-info" is. I use the header Accept application/ld+json.

**Comment by jnehring** [comment]
We found out that WRIPL does not use the filters so this issue is obsolete. Francisc, you can use the Most Frequent Sense on freme-dev directly and after the next release you can use it on freme-live
