### ISSUE TITLE
Make sparql endpoint publicly available

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-services#54]
We will remove all references to our old servers from the e-link templates. Therefore we need to update the SPARQL endpoint. Please make the SPARQL endpoint publicly available at

https://api.freme-project.eu/sparql

This should be a proxy redirect from /sparql to http://localhost:8890/sparql .

We are updating the e-link template endpoints in this issue: https://github.com/freme-project/basic-services/issues/117

**Comment by munnellg** [comment]
Endpoint is now available
