### ISSUE TITLE
No more templates in e-Link

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-services#8]
[This link](http://api-dev.freme-project.eu/current/e-link/manage) shows that there are no templates in the database on freme-dev. The MySQL table contains 42 rows.

**Comment by jnehring** [comment]
The link has changed: http://api-dev.freme-project.eu/current/e-link/templates

But it still does not work.

**Comment by ArneBinder** [comment]
this is part of [this issue](https://github.com/freme-project/FREMECommon/issues/20)
